### PR TITLE
Jupyter notebook for running cartpole in FFL using rllib

### PR DESCRIPTION
**Pull request by velmurugan-r**
This PR includes
Jupyter notebook to run a cartpole experiment using FFL and RLlib library and the feature includes
a. Define aggregator configuration and running aggregator
b. Define party configuration and start the parties and register to the aggregator
c. Train and evaluate the results
d. Visualize the evaluation results using matplotlib
e. Supports multiple parties configuration.

### CODE REVIEW

**Review by Yi-Zoey — APPROVED** [review]
Looks great! Thanks!

**Review by chalianwar — APPROVED** [review]
Looks good. Thanks!

**Comment by chalianwar** [comment]
One minor comment. It would be great if you add an entry to following file:
https://github.com/IBM/federated-learning-lib/blob/main/examples/README.md

**Comment by velmurugan-r** [comment]
@chalianwar updated examples/README to add jupyter notebook for cartpole

**Comment by chalianwar** [comment]
Thanks!

**Pull request merged**
